default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  username: <%= ENV.fetch("DB_USER") { "rails" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>

development:
  <<: *default
  database: db_development

test:
  <<: *default
  database: db_test

production:
  primary:
    <<: *default
    database: db_production
  cache:
    <<: *default
    database: db_production
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: db_production
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: db_production
    migrations_paths: db/cable_migrate